# Generated by Django 3.1.6 on 2021-02-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0003_auto_20210208_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitespurchaserequest',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
