# Generated by Django 3.1.6 on 2021-02-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20210207_1523'),
        ('purchase_request', '0004_sitespurchaserequest_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpurchaserequest',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainorder_rev', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='sitespurchaserequest',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siteorder_rev', to='sites.site'),
        ),
    ]
